services:
  postgres_bd:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=elements'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5432'

  telegram_service:
    build:
      dockerfile: Dockerfile
    ports:
      - "9235:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_bd:5432/elements
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      TG_BOT_NAME: ${TG_BOT_NAME}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
volumes:
  db_data:
